// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: fb01cdf859da4b36c0080d256d40bb7dd5cfa5474da5ed4c8e1f6eb126b89b6e


/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "esds-theme";

export const themeNames: ThemeName[] = ["esds-theme"];

export type KcEnvName = "FDN_THEME_PRIMARY_COLOR" | "FDN_THEME_SECONDARY_COLOR";

export const kcEnvNames: KcEnvName[] = ["FDN_THEME_PRIMARY_COLOR", "FDN_THEME_SECONDARY_COLOR"];

export const kcEnvDefaults: Record<KcEnvName, string> = {
  "FDN_THEME_PRIMARY_COLOR": "#1976d2",
  "FDN_THEME_SECONDARY_COLOR": "#9c27b0"
};

/**
 * NOTE: Do not import this type except maybe in your entrypoint. 
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext =
    | import("./login/KcContext").KcContext
    ;

declare global {
    interface Window {
        kcContext?: KcContext;
    }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));

export function KcPage(
    props: {
        kcContext: KcContext;
        fallback?: ReactNode;
    }
) {
    const { kcContext, fallback } = props;
    return (
        <Suspense fallback={fallback}>
            {(() => {
                switch (kcContext.themeType) {
                    case "login": return <KcLoginPage kcContext={kcContext} />;
                }
            })()}
        </Suspense>
    );
}
